/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package congto_ui;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author minhc
 */
public class CongTo_UI extends javax.swing.JFrame {
    public static connectDB connection = new connectDB();

    /**
     * Creates new form HocSinh_UI
     */
    public CongTo_UI() {
        initComponents();
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSoCT = new javax.swing.JTextField();
        txtChuHo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoCu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoMoi = new javax.swing.JTextField();
        btnThemMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCongTo = new javax.swing.JTable();
        btnCapNhat = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Số công tơ");

        txtSoCT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtChuHo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên chủ hộ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Số cũ");

        txtSoCu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số mới");

        txtSoMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblCongTo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Số CT", "Chủ hộ", "Số cũ", "Số mới", "Số tiêu thụ", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCongTo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCongToMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCongTo);

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Đơn giá");

        txtDonGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tìm kiếm");

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChuHo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoCu, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoMoi, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoCT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSoCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMoi)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadData(){
        String SQL = "select * from `congto`";
        ResultSet rs = connection.ExcuteQueryGetTable(SQL);
        Object [] obj = new Object[]{"Số CT","Chủ hộ","Số cũ","Số mới","Sô tiêu thụ","Thành tiền"};
        DefaultTableModel tableModel = new DefaultTableModel(obj,0);
        tblCongTo.setModel(tableModel);
        try{
            while(rs.next()){
                Object[] item = new Object[6];
                CongTo hs = new CongTo(rs);
                item[0] = hs.getSoCT();
                item[1] = hs.getChuHo();
                item[2] = hs.getSoCu();
                item[3] = hs.getSoMoi();
                item[4] = hs.getSoDien();
                item[5] = hs.getThanhTien();
                tableModel.addRow(item);
            }
        }
        catch (Exception e) {
            System.out.println(e.toString());
        }
        clearText();
        setWidthColumn();
        disableButton();
    }
    
    private CongTo findCongToById(String SoCT){
        String SQL = "select * from `congto` where `congto`.`SoCT` = '"+SoCT+"'";
        ResultSet rs = connection.ExcuteQueryGetTable(SQL);
        try {
            if(rs.next())
                return new CongTo(rs);
            else
                return null;
        } catch (Exception e) {
            return null;
        }
    }
    
    private void findCongToByChuHo(){
        String SQL = "select * from `congto` where `ChuHo` like '%"+txtSearch.getText()+"%'";
        ResultSet rs = connection.ExcuteQueryGetTable(SQL);
        Object [] obj = new Object[]{"Số CT","Chủ hộ","Số cũ","Số mới","Sô tiêu thụ","Thành tiền"};
        DefaultTableModel tableModel = new DefaultTableModel(obj,0);
        tblCongTo.setModel(tableModel);
        try{
            while(rs.next()){
                Object[] item = new Object[6];
                CongTo hs = new CongTo(rs);
                item[0] = hs.getSoCT();
                item[1] = hs.getChuHo();
                item[2] = hs.getSoCu();
                item[3] = hs.getSoMoi();
                item[4] = hs.getSoDien();
                item[5] = hs.getThanhTien();
                tableModel.addRow(item);
            }
        }
        catch (Exception e) {
            System.out.println(e.toString());
        }
        clearText();
        setWidthColumn();
        disableButton();
    }
    
    private void disableButton(){
        if(tblCongTo.getSelectedRow()==-1){
            btnCapNhat.setEnabled(false);
            btnXoa.setEnabled(false);
        }
        else{
            btnCapNhat.setEnabled(true);
            btnXoa.setEnabled(true);
        }
    }
    
    private void setWidthColumn(){
        tblCongTo.getColumnModel().getColumn(0).setPreferredWidth(20);
        tblCongTo.getColumnModel().getColumn(1).setPreferredWidth(130);
        tblCongTo.getColumnModel().getColumn(2).setPreferredWidth(30);
        tblCongTo.getColumnModel().getColumn(3).setPreferredWidth(40);
        tblCongTo.getColumnModel().getColumn(4).setPreferredWidth(50);
        tblCongTo.getColumnModel().getColumn(5).setPreferredWidth(50);
    }
    
    private void clearText(){
        txtSoCT.setText("");
        txtChuHo.setText("");
        txtSoCu.setText("");
        txtSoMoi.setText("");
        txtDonGia.setText("");
    }
    
    private int checkIdExist(){
        try {
            String SQL = "select count(*) as `count` from `congto` where `congto`.`SoCT` = '"+txtSoCT.getText()+"'";
            ResultSet rs = connection.ExcuteQueryGetTable(SQL);
            return rs.next()?rs.getInt("count"):10;
        } catch (SQLException ex) {
            System.out.println("error");
            return 10;
        }
    }
    
    private boolean checkInvalid(){
        if(txtSoCT.getText().isEmpty() || txtChuHo.getText().isEmpty() || txtSoCu.getText().isEmpty() || txtSoMoi.getText().isEmpty() || txtDonGia.getText().isEmpty())
                return false;
        try {
            Integer.parseInt(txtSoCu.getText());
        } catch (Exception e) {
            return false;
        }
        try {
            Integer.parseInt(txtSoMoi.getText());
        } catch (Exception e) {
            return false;
        }
        try {
            Integer.parseInt(txtDonGia.getText());
        } catch (Exception e) {
            return false;
        }
        if(Integer.parseInt(txtSoMoi.getText())<Integer.parseInt(txtSoCu.getText()))
            return false;
        return true;
    }
    
    private boolean checkIdExistToUpdate(int index){
        int count = 0;
        for(int i = 0;i<tblCongTo.getModel().getRowCount();i++){
            if(i == index)
                continue;
            if(txtSoCT.getText().equals(tblCongTo.getModel().getValueAt(i, 0))){
                count ++;
            }
        }
        return count<1;
    }
    
    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        if(checkInvalid()){
            if(checkIdExist()<=0){
                String SQL = "insert into `congto` (`SoCT`, `ChuHo`,`SoCu`,`SoMoi`,`DonGia`) VALUES ('"+txtSoCT.getText()+"','"+txtChuHo.getText()+"','"+txtSoCu.getText()+"','"+txtSoMoi.getText()+"','"+txtDonGia.getText()+"')";
                connection.ExcuteQueryUpdateDB(SQL);
                LoadData();
            }
            else{
                JOptionPane.showMessageDialog(null, "Mã công tơ đã tồn tại!");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Thông tin không hợp lệ!");
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(checkInvalid()){
            String SQL = "DELETE FROM `congto` WHERE `congto`.`SoCT` = '"+txtSoCT.getText()+"'";
            connection.ExcuteQueryUpdateDB(SQL);
            LoadData();
        }
        else
            JOptionPane.showMessageDialog(null, "Thông tin không hợp lệ!");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblCongToMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCongToMouseClicked
        // TODO add your handling code here:
        int index = tblCongTo.getSelectedRow();
        CongTo ct;
        ct = findCongToById(tblCongTo.getValueAt(index, 0).toString());
        txtSoCT.setText(tblCongTo.getValueAt(index, 0).toString());
        txtChuHo.setText(tblCongTo.getValueAt(index, 1).toString());
        txtSoCu.setText(tblCongTo.getValueAt(index, 2).toString());
        txtSoMoi.setText(tblCongTo.getValueAt(index, 3).toString());
        txtDonGia.setText(String.valueOf(ct.getDonGia()));
        disableButton();
    }//GEN-LAST:event_tblCongToMouseClicked

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        if(checkInvalid()){
            if(checkIdExistToUpdate(tblCongTo.getSelectedRow())){
                String SQL = "update `congto` set `ChuHo` = '"+txtChuHo.getText()+"', `SoCT` = '"+txtSoCT.getText() + "', `SoCu` = "+txtSoCu.getText()+ ", `SoMoi` = "+txtSoMoi.getText()+ ", `DonGia` = "+txtDonGia.getText()+" where `SoCT` = '"+tblCongTo.getValueAt(tblCongTo.getSelectedRow(), 0).toString() +"'";
                connection.ExcuteQueryUpdateDB(SQL);
                LoadData();
            }
            else
                JOptionPane.showMessageDialog(null, "Mã công tơ đã tồn tại!");
        }
        else
            JOptionPane.showMessageDialog(null, "Thông tin không hợp lệ!");
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        if(txtSearch.getText().isEmpty())
            LoadData();
        else findCongToByChuHo();
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CongTo_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CongTo_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CongTo_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CongTo_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CongTo_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCongTo;
    private javax.swing.JTextField txtChuHo;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoCT;
    private javax.swing.JTextField txtSoCu;
    private javax.swing.JTextField txtSoMoi;
    // End of variables declaration//GEN-END:variables
}
